### ISSUE TITLE
能否添加对6.0的支持

### ISSUE THREAD

**Issue by AndyGu** [hujiaweibujidao/mupdf#1]
请教下libmupdf.so是您自己生成的么？能否添加对6.0的支持？

**Comment by hujiaweibujidao** [comment]
@AndyGu 是我自己生成的。但是这个基于很多年以前的mupdf，我也一直没有改动，所以建议你参考[mupdf](http://www.mupdf.com/) 官网上的文档和资料，谢谢关注。
