### ISSUE TITLE
License issue: MuPDF is GNU AGPL licensed

### ISSUE THREAD

**Issue by robinwatts** [hujiaweibujidao/mupdf#2]
MuPDF is released under the GNU AGPL. As such your code also needs to be licensed under the GNU APGL. You need to supply a copy of the license terms, and a pointer to where people can get the source from.

Please either do this, or take this repo down.

Thanks.

**Comment by hujiaweibujidao** [comment]
@robinwatts Thank you for reminding that, license is now supplied. Thanks. 👍

**Comment by robinwatts** [comment]
"You should have received a copy of the GNU Affero General Public License along with this program"

You should commit a copy of the license into the top of your project. Also, you should state exactly what version of MuPDF you used to create the binaries for the libraries you include.

Thanks!

**Comment by hujiaweibujidao** [comment]
@robinwatts I already forget what version of MuPDF I used. I think I'd better take this repo down.
